---
- name: clone repo
  git:
    repo: "{{ config_repo }}"
    dest: ./config
    force: true
  delegate_to: 127.0.0.1
  changed_when: false
  become: false
  when: GIT_USER is not defined

- name: clone repo via pw
  git:
    repo: https://{{ GIT_USER | urlencode }}:{{ GIT_PWD | urlencode }}@{{ config_repo }}
    dest: ./config
    force: true
  delegate_to: 127.0.0.1
  changed_when: false
  become: false
  when: GIT_USER is defined


- name: load vault config
  include_vars: ./config/config_vault.yaml
  delegate_to: 127.0.0.1
  changed_when: false
  become: false

- name: load config
  include_vars: ./config/config.yaml
  delegate_to: 127.0.0.1
  changed_when: false
  become: false
